### ISSUE TITLE
Find and prepare tools to ease workflow

### ISSUE THREAD

**Issue by Nobody-Special** [Poniedzialkowi-Inzynierowie/CherryApp#1]
### Report No. 1:
Current language is rust, backed with cargo _project manager_. It would be nice to have support for jade (pug), sass, and some js-minifier and ecma-script.

**Comment by Nobody-Special** [comment]
After some hour and one full mug of coffee I can say, that it's doable. However it doesn't cover all border cases. 

- **EcmaScript** support was the easiest one to find: _[parcel-redux](https://github.com/nathan/parcel-redux)_
- **Sass** was a bit harder, but in the end we can settle down with: _[rsass](https://docs.rs/rsass/0.3.4/rsass/)_
- **Jade** is pain in the ass, as it basically doesn't exist.

**Comment by fastfend** [comment]
Closing issue. We're no longer using rust.
